import Head from 'next/head';
import { Red_Hat_Display, Cedarville_Cursive, Special_Elite, Pirata_One } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const redHat = Red_Hat_Display({
  variable: "--font-red-hat",
  subsets: ["latin"],
  weight: ["400", "700"]
});

const cederville = Cedarville_Cursive({
  variable: "--font-cederville-cursive",
  subsets: ["latin"],
  weight: ["400"],
});

const specialElite = Special_Elite({
  variable: "--font-special-elite",
  subsets: ["latin"],
  weight: ["400"]
});

const pirataOne = Pirata_One({
  variable: "--font-pirata-one",
  subsets: ["latin"],
  weight: ["400"]
});

const gidole = localFont({
  variable: "--font-gidole",
  src: [
    {
      path: "./fonts/gidole.ttf",
      weight: "400",
      style: "normal"
    }
  ],
  display: "swap"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html
      className={`${redHat.variable} ${cederville.variable} ${specialElite.variable} ${pirataOne.variable} ${gidole.variable}`}
      lang="en"
    >
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </Head>
      <body>{children}</body>
    </html>
  );
}

